### PR TITLE
Add SSHFS support

### PR DESCRIPTION
**Pull request by alhirzel**
I have started the process of implementing SSHFS. I am doing this against v1.5 (because that's the release I started with). The following has been done:

  - [x] WebUI support for adding/removing SSHFS mounts
  - [x] Testing against v1.5; this works for me on my RaspPI using SSH keys after doing lots of manual steps

At least the following needs to be done before this can be merged:

  - [ ] Update rootfs (see below for info on changes)
  - [ ] Support a password (i.e. support not using SSH keys)
      * should not be too hard, just haven't looked at it yet
  - [ ] Support options (e.g. arcfour cipher, others)
  - [ ] Any other updates in the documentation/webui
  - [ ] Testing

Rootfs changes
--------------

To get this working, I did the following starting with a fresh install of v1.5
for the Raspberry PI:

  * `apt-get update` (probably overkill...)
  * `apt-get install sshfs fuse libfuse2` (installs `sshfs` and `libfuse2`, and upgrades `fuse`)
    ```
root@volumio:/DEVEL/mywebui# dpkg -l sshfs libfuse2 fuse | tail -n3
ii  fuse                             2.9.3-15                           armhf        Filesystem in Userspace
ii  libfuse2:armhf                   2.9.3-15                           armhf        Filesystem in Userspace (library)
ii  sshfs                            2.5-1                              armhf        filesystem client based on SSH File Transfer Protocol
```

  * added `pi` to the `fuse` group
  * uncommented `user_allow_other` in `/etc/fuse.conf`
  * used `ssh-keygen` as root to generate /root/.ssh/id_rsa.pub
  * added this public key to the `~/.ssh/authorized_keys` file on my server

### CODE REVIEW

**Comment by volumio** [comment]
Interesting! But, since we are working now on a new version (based on node js), the current UI will be dropped.Please tell me your username, and I'll add you to dev group, so you can join the development of new webui.
Also, the new system will be built with this build script:https://github.com/volumio/Build

Date: Sun, 1 Feb 2015 14:06:42 -0800

**Comment by alhirzel** [comment]
I made my changes just in time, then... lol

My username is alhirzel, I would definitely help by implementing this feature. Thanks!

**Comment by volumio** [comment]
Great! You can noo see developer's corner.I'll suggest to take a look also at the buildscripts, if you need help. let me know! 

Date: Sun, 1 Feb 2015 14:16:37 -0800

**Comment by alhirzel** [comment]
Where is developer's corner?

**Comment by volumio** [comment]
https://volumio.org/forum/developer-corner-f30.html
Can you see it?

Date: Mon, 2 Feb 2015 12:39:43 -0800

**Comment by alhirzel** [comment]
Oh on the Forums, got it. Works, thanks!

**Comment by jomo** [comment]
Is there a GitHub repo for the node-based version?

**Comment by ning-yu** [comment]
> Is there a GitHub repo for the node-based version?

Yes, we'll make it public when it's ready for beta testing!

**Comment by ning-yu** [comment]
@alhirzel @volumio 
I'm closing this pull request since it sounds like we want to leave this for the next Volumio revision.

**Comment by jomo** [comment]
Why don't you make the new repo public already?
I would love to take a look and maybe contribute as well.

**Comment by ning-yu** [comment]
Sure, you're welcome to help! I'll send Michelangelo a PM to see if we can give you access to the repo and forum section.

**Comment by volumio** [comment]
Yes I'll give you access! And I think its time to make the repo public!

**Comment by jomo** [comment]
:+1: great!

**Comment by jomo** [comment]
Could you add [me](https://volumio.org/forum/member3230.html) to the internal discussion forum?
Sorry for spamming this issue, I can't send PMs on the forum :/

**Comment by volumio** [comment]
Done! We'll also have a meeting in 3 hours! Join us!

**Comment by jomo** [comment]
Where do I join?

**Comment by ning-yu** [comment]
@jomo I sent you a forum PM

**Pull request closed without merging**
