### PR TITLE
Browse Tab Empty fix

### PR DESCRIPTION
**Pull request by montaintop**
Details below

Thanks to DARKHalf  for his initial patch, I added one little tweak so if it is already at top of the folder, back button won't go back to empty

https://volumio.org/forum/browse-tab-empty-t3897.html

### CODE REVIEW

**Comment by norrest** [comment]
imgpsh_fullsize
Dont help!

**Comment by volumio** [comment]
Thank you for your PR... But we dropped 1.55 and are working on 2...

**Comment by norrest** [comment]
so how to solve this problem?)

**Comment by volumio** [comment]
download volumio 2 ;)
https://volumio.org/get-started/

**Pull request closed without merging**
